# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клієнт', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'verbose_name': 'Лiки', 'verbose_name_plural': 'Лiки'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': 'Прийом ліків', 'verbose_name_plural': 'Прийом ліків'},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'verbose_name': 'Процедура', 'verbose_name_plural': 'Процедури (календар клієнтiв)'},
        ),
        migrations.AlterModelOptions(
            name='procedure_name',
            options={'verbose_name': 'Назва процедури', 'verbose_name_plural': 'Перелiк процедур'},
        ),
        migrations.AlterModelOptions(
            name='procedure_type',
            options={'verbose_name': 'Вид процедури', 'verbose_name_plural': 'Процедури (фiнанси)'},
        ),
        migrations.AddField(
            model_name='procedure_name',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Опис процедури'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, verbose_name='Рекомендації'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='data_end',
            field=models.DateField(verbose_name='Дата кiнця прийому'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='data_start',
            field=models.DateField(verbose_name='Дата початку прийому'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='time_end',
            field=models.DateTimeField(verbose_name='Час кiнця'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='time_start',
            field=models.DateTimeField(verbose_name='Час початку'),
        ),
        migrations.AlterField(
            model_name='procedure_name',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва процедури'),
        ),
        migrations.AlterField(
            model_name='procedure_type',
            name='consumable',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='procedure_type',
            name='cost',
            field=models.IntegerField(verbose_name='Вартiсть для '),
        ),
        migrations.AlterField(
            model_name='procedure_type',
            name='prime_cost',
            field=models.IntegerField(verbose_name='Собiвартiсть'),
        ),
    ]
