# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-20 11:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant', '0002_auto_20161206_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(max_length=50, verbose_name='Назва')),
                ('text_news', models.TextField(blank=True, verbose_name='Опис')),
                ('image_news', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата розміщення')),
            ],
            options={
                'verbose_name_plural': 'Новини',
            },
        ),
    ]
